### ISSUE TITLE
Gibt es sowas nicht schon? ;-)

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yakicon#1]
https://github.com/FriendsOfREDAXO/iconpicker

**Comment by tbaddade** [comment]
Ja gibt es. Unser AddOn nannte sich ebenfalls Iconpicker und wurde vor Peters Addon entwickelt. Da ich vergaß den Key bei MyRedaxo zu registrieren, waren dann zwei AddOns mit demselben Namen unterwegs. Problem war jetzt gestern, dass jemand den iconpicker via Installer aktualisiert hatte und damit das FOR-AddOn über das Unserige drüber bügelte. Deshalb gestern ein Backup wiederhergestellt, Addon umbenannt und als Sicherung zusätzlich auf Github geladen.
